### ISSUE TITLE
Mail sending issue

### ISSUE THREAD

**Issue by OzzyOzmen** [moulibheemaneti/mb_contact_form#1]
The mail can not sending when click to the button even destination email is true. ( i tried with the gmail and hotmail both ).
So do we have to use any provider for implementing to our project for make this "mb_contact_form" works correctly ? ( i mean sending successfully ) ?

**Comment by moulibheemaneti** [comment]
Hey there.
Sorry for the late reply.
Thank you for reaching out with this issue. But unfortunately I haven't added any provider. When button is clicked the screen would redirect to the
mail app in your device and then you need to click the send button.
Hope this helps. If not feel free to get back to me.

Future updates: 
- UI update

Thank you.

**Comment by OzzyOzmen** [comment]
Hi thanks. Anfortunetely its not redirecting to the an email app on mobile. ( i tried it on ios emulator.)

**Comment by moulibheemaneti** [comment]
> Hi thanks. Anfortunetely its not redirecting to the an email app on mobile. ( i tried it on ios emulator.)

Hey once again. I'm sorry for not being active with this package. 
I'll start working on this issue and give you the updates within a week.

**Comment by OzzyOzmen** [comment]
hi probably it wont work yeah ?

**Comment by moulibheemaneti** [comment]
> hi probably it wont work yeah ?

Yeah it's not working. If you find any fix, please kindly let me know.

**Comment by moulibheemaneti** [comment]
Since there is no further issue here. I'm closing this issue.
